import Head from "next/head";
import Image from "next/image";
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Values from '../components/Values';
import Teachers from '../components/Teachers';
import Student from '../components/Student';
import MoreInfoModal from '../components/MoreInfoModal';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Personalized Learning Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero/>
      <Values/>
      <Teachers/>
      <Student/>
      <MoreInfoModal/>
    
    </div>
  );
}
